version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rocky-web-app"
s3_bucket = "rockysamstack"
s3_prefix = "rocky-web-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
